services:
  qa:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: histotools/quickannotator:local
    command: 
      /bin/bash
    group_add:
      - ${GID}
    volumes:
      - ..:/opt/QuickAnnotator
    cap_add:
      - SYS_PTRACE
