services:
  qa:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: histotools/quickannotator:local
    volumes:
      - ..:/opt/QuickAnnotator
    cap_add:
      - SYS_PTRACE
