services:
  qa:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: histotools/quickannotator:local
    group_add:
      - ${UID}
    volumes:
      - ..:/opt/QuickAnnotator
    cap_add:
      - SYS_PTRACE
